/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AuthenticatedVerifyPrnRouteImport } from './routes/_authenticated.verify-prn'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedMyTicketsRouteImport } from './routes/_authenticated.my-tickets'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedTicketsIdRouteImport } from './routes/_authenticated.tickets.$id'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated.admin.students'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminScannerRouteImport } from './routes/_authenticated.admin.scanner'
import { Route as AuthenticatedAdminRegistrationsRouteImport } from './routes/_authenticated.admin.registrations'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated.admin.events'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated.admin.analytics'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAdminEventsNewRouteImport } from './routes/_authenticated.admin.events.new'
import { Route as AuthenticatedAdminEventsIdEditRouteImport } from './routes/_authenticated.admin.events.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyPrnRoute = AuthenticatedVerifyPrnRouteImport.update({
  id: '/verify-prn',
  path: '/verify-prn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyTicketsRoute = AuthenticatedMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedTicketsIdRoute = AuthenticatedTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminScannerRoute =
  AuthenticatedAdminScannerRouteImport.update({
    id: '/scanner',
    path: '/scanner',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRegistrationsRoute =
  AuthenticatedAdminRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminEventsNewRoute =
  AuthenticatedAdminEventsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminEventsRoute,
  } as any)
const AuthenticatedAdminEventsIdEditRoute =
  AuthenticatedAdminEventsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/verify-prn': typeof AuthenticatedVerifyPrnRoute
  '/events/$slug': typeof EventsSlugRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/events/': typeof EventsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/scanner': typeof AuthenticatedAdminScannerRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/events/$id/edit': typeof AuthenticatedAdminEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/verify-prn': typeof AuthenticatedVerifyPrnRoute
  '/events/$slug': typeof EventsSlugRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/events': typeof EventsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/scanner': typeof AuthenticatedAdminScannerRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/admin/events/$id/edit': typeof AuthenticatedAdminEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/verify-prn': typeof AuthenticatedVerifyPrnRoute
  '/events/$slug': typeof EventsSlugRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/events/': typeof EventsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/_authenticated/admin/scanner': typeof AuthenticatedAdminScannerRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/admin/events/$id/edit': typeof AuthenticatedAdminEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/my-tickets'
    | '/profile'
    | '/verify-prn'
    | '/events/$slug'
    | '/verify/$token'
    | '/events/'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/scanner'
    | '/admin/settings'
    | '/admin/students'
    | '/tickets/$id'
    | '/admin/'
    | '/admin/events/new'
    | '/api/public/payments/webhook'
    | '/admin/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/my-tickets'
    | '/profile'
    | '/verify-prn'
    | '/events/$slug'
    | '/verify/$token'
    | '/events'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/scanner'
    | '/admin/settings'
    | '/admin/students'
    | '/tickets/$id'
    | '/admin'
    | '/admin/events/new'
    | '/api/public/payments/webhook'
    | '/admin/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/my-tickets'
    | '/_authenticated/profile'
    | '/_authenticated/verify-prn'
    | '/events/$slug'
    | '/verify/$token'
    | '/events/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/registrations'
    | '/_authenticated/admin/scanner'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/students'
    | '/_authenticated/tickets/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/events/new'
    | '/api/public/payments/webhook'
    | '/_authenticated/admin/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  EventsSlugRoute: typeof EventsSlugRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify-prn': {
      id: '/_authenticated/verify-prn'
      path: '/verify-prn'
      fullPath: '/verify-prn'
      preLoaderRoute: typeof AuthenticatedVerifyPrnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-tickets': {
      id: '/_authenticated/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof AuthenticatedMyTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/tickets/$id': {
      id: '/_authenticated/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AuthenticatedTicketsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/scanner': {
      id: '/_authenticated/admin/scanner'
      path: '/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AuthenticatedAdminScannerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/registrations': {
      id: '/_authenticated/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/events/new': {
      id: '/_authenticated/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AuthenticatedAdminEventsNewRouteImport
      parentRoute: typeof AuthenticatedAdminEventsRoute
    }
    '/_authenticated/admin/events/$id/edit': {
      id: '/_authenticated/admin/events/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/events/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminEventsRoute
    }
  }
}

interface AuthenticatedAdminEventsRouteChildren {
  AuthenticatedAdminEventsNewRoute: typeof AuthenticatedAdminEventsNewRoute
  AuthenticatedAdminEventsIdEditRoute: typeof AuthenticatedAdminEventsIdEditRoute
}

const AuthenticatedAdminEventsRouteChildren: AuthenticatedAdminEventsRouteChildren =
  {
    AuthenticatedAdminEventsNewRoute: AuthenticatedAdminEventsNewRoute,
    AuthenticatedAdminEventsIdEditRoute: AuthenticatedAdminEventsIdEditRoute,
  }

const AuthenticatedAdminEventsRouteWithChildren =
  AuthenticatedAdminEventsRoute._addFileChildren(
    AuthenticatedAdminEventsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRouteWithChildren
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminRegistrationsRoute: typeof AuthenticatedAdminRegistrationsRoute
  AuthenticatedAdminScannerRoute: typeof AuthenticatedAdminScannerRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRouteWithChildren,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminRegistrationsRoute: AuthenticatedAdminRegistrationsRoute,
  AuthenticatedAdminScannerRoute: AuthenticatedAdminScannerRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMyTicketsRoute: typeof AuthenticatedMyTicketsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVerifyPrnRoute: typeof AuthenticatedVerifyPrnRoute
  AuthenticatedTicketsIdRoute: typeof AuthenticatedTicketsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMyTicketsRoute: AuthenticatedMyTicketsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVerifyPrnRoute: AuthenticatedVerifyPrnRoute,
  AuthenticatedTicketsIdRoute: AuthenticatedTicketsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  EventsSlugRoute: EventsSlugRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
